
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function NotesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <h1>Notes Header</h1>
        {children}
        <h1>Notes Footer</h1>
    </>
   
  )
}
