import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Main Header</h1>
        <Link style={{marginLeft: "30px"}} href={"/notes"}>Notes</Link>
        <Link style={{marginLeft: "30px"}} href={"/dashboard"}>Dashboard</Link>
        <Link style={{marginLeft: "30px"}} href={`/notes/${3}`}>Note 3</Link>
        <Link style={{marginLeft: "30px"}} href={"/notes/search"}>Search</Link>
        {children}
        <h1>Main Footer</h1>
        </body>
    </html>
  )
}
